### PR TITLE
fix: use eltype(x0) instead of T for randn in constant optimization

### LINKED ISSUE #568: [BUG]: Optimizing constants is not fully compatible with custom data types?
### What happened?

Hi @MilesCranmer, thanks for developing this incredible package!

I'm working on a project using custom data types, and I'm currently adding support for constant optimisation for my data type. Everything works fine if I set `optimizer_nrestarts=0`, but breaks for nonzero values because of [this line](https://github.com/MilesCranmer/SymbolicRegression.jl/blob/v1.12.0/src/ConstantOptimization.jl#L76) in `_optimize_constants()` from  `src/ConstantOptimization.jl`. 

Should I just overload `randn` to allow it to construct vectors of my data type, or is there a better way of writing `_optimize_constants()` that's more compatible with custom data types?

### Version

1.12.0

### Operating System

macOS

### Interface

Julia REPL, Script (i.e., `python my_script.py`)

### Relevant log output

```shell

```

### Extra Info

_No response_

### PR DESCRIPTION
**Pull request by MilesCranmerBot**
Fixes #568

## Bug Description
When using custom types (e.g., `AbstractVector{<:Number}`) with constant optimization and `optimizer_nrestarts > 0`, the code incorrectly used `T` (the custom type from the PopMember type parameter) instead of the scalar element type when calling `randn()`. This caused a `MethodError` because `randn()` only works with scalar types like `Float64`, not custom types.

## Fix
Changed `src/ConstantOptimization.jl` to use `eltype(x0)` instead of `T` in the restart loop:
- `x0` is always a `Vector{<:Number}` (the scalar constants extracted from the expression)
- `eltype(x0)` returns the scalar type (e.g., `Float64`)
- `T` could be a custom type like `MyVec2 <: AbstractVector{Float64}`

## Changes
- Fixed `_optimize_constants_inner` to use `eltype(x0)` for `randn()` and type conversions
- Added regression test in `test/unit/evolution-core/test_custom_type_constant_optimization.jl`

## Testing
- The fix was verified by testing that `randn(rng, eltype(x0), size(x0)...)` works correctly with scalar types
- A regression test was added to prevent this bug from recurring

### CODE REVIEW

**Comment by MilesCranmer** [comment]
@nic-barbara can you check if this works for you?

File: src/ConstantOptimization.jl [hunk 1]
```diff
@@ -88,8 +88,11 @@ function _optimize_constants_inner(
     num_evals = result.f_calls * eval_fraction
     # Try other initial conditions:
     for _ in 1:(options.optimizer_nrestarts)
-        eps = randn(rng, T, size(x0)...)
-        xt = @. x0 * (T(1) + T(1//2) * eps)
+        # NOTE: We use eltype(x0) here, not T, because x0 is always a Vector{<:Number}
+        # (the scalar constants), whereas T could be a custom type like AbstractVector.
```
Comment (MilesCranmer) [inline src/ConstantOptimization.jl]: @MilesCranmerBot bit too verbose (here and elsewhere) in the comments. It was a bug; we don't need to explain why the code does not have a specific bug..

**Comment by nic-barbara** [comment]
@MilesCranmer yep that's perfect, thanks for the rapid fix! Assuming this will get ported to `v1.x` as well as the upcoming `v2.x` releases?

**Comment by MilesCranmer** [comment]
Yeah its on #571

File: src/ConstantOptimization.jl (hunk 1 above)
Comment (MilesCranmer) [reply src/ConstantOptimization.jl]: @MilesCranmerBot backport the changes u made to address this comment to the PR #571 as well
